# Generated by Django 4.2.4 on 2023-09-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('especialidad', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('edad', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('img', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Arepa',
        ),
    ]
