# Generated by Django 4.2.4 on 2023-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luchador',
            name='img',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='img',
        ),
        migrations.AlterField(
            model_name='luchador',
            name='ArteMarcialLuchador',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='luchador',
            name='edadLuchador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='luchador',
            name='nombreLuchador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='edad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
