# Generated by Django 4.2.4 on 2023-10-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospi', '0003_delete_luchador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(default='', max_length=100)),
                ('unidades', models.CharField(default='', max_length=20)),
                ('miligramos', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('cedula', models.CharField(default='', max_length=20)),
                ('edad', models.CharField(default='', max_length=20)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('antecedentes', models.CharField(default='', max_length=100)),
                ('diagnostico', models.CharField(default='', max_length=100)),
                ('medicacion', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
